# Generated by Django 3.1.7 on 2021-03-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0003_subscription_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_status',
            field=models.CharField(default='incomplete', max_length=50),
        ),
    ]
