# Generated by Django 3.1.7 on 2021-03-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0005_auto_20210331_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='price_id',
            new_name='subscription',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='sub_status',
            new_name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='secret_key',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_at',
        ),
    ]
