# Generated by Django 3.1.7 on 2021-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0006_auto_20210331_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
