# Generated by Django 3.1.7 on 2021-03-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0007_auto_20210331_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment_status',
        ),
    ]
