# Generated by Django 2.1.5 on 2021-02-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='create',
            new_name='created',
        ),
    ]
