# Generated by Django 3.1.7 on 2021-03-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_id',
        ),
    ]
